/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as PolitiqueCookiesRouteImport } from './routes/politique-cookies'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as EspaceClientRouteImport } from './routes/espace-client'
import { Route as CodeDeLaRouteRouteImport } from './routes/code-de-la-route'
import { Route as CalculateurBonusMalusRouteImport } from './routes/calculateur-bonus-malus'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceAssuranceVtcRouteImport } from './routes/service.assurance-vtc'
import { Route as ServiceAssuranceSanteRouteImport } from './routes/service.assurance-sante'
import { Route as ServiceAssuranceProRouteImport } from './routes/service.assurance-pro'
import { Route as ServiceAssurancePrevoyanceRouteImport } from './routes/service.assurance-prevoyance'
import { Route as ServiceAssuranceMotoRouteImport } from './routes/service.assurance-moto'
import { Route as ServiceAssuranceHabitationRouteImport } from './routes/service.assurance-habitation'
import { Route as ServiceAssuranceDecennaleRouteImport } from './routes/service.assurance-decennale'
import { Route as ServiceAssuranceAutoRouteImport } from './routes/service.assurance-auto'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const PolitiqueCookiesRoute = PolitiqueCookiesRouteImport.update({
  id: '/politique-cookies',
  path: '/politique-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceClientRoute = EspaceClientRouteImport.update({
  id: '/espace-client',
  path: '/espace-client',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeDeLaRouteRoute = CodeDeLaRouteRouteImport.update({
  id: '/code-de-la-route',
  path: '/code-de-la-route',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculateurBonusMalusRoute = CalculateurBonusMalusRouteImport.update({
  id: '/calculateur-bonus-malus',
  path: '/calculateur-bonus-malus',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAssuranceVtcRoute = ServiceAssuranceVtcRouteImport.update({
  id: '/service/assurance-vtc',
  path: '/service/assurance-vtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAssuranceSanteRoute = ServiceAssuranceSanteRouteImport.update({
  id: '/service/assurance-sante',
  path: '/service/assurance-sante',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAssuranceProRoute = ServiceAssuranceProRouteImport.update({
  id: '/service/assurance-pro',
  path: '/service/assurance-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAssurancePrevoyanceRoute =
  ServiceAssurancePrevoyanceRouteImport.update({
    id: '/service/assurance-prevoyance',
    path: '/service/assurance-prevoyance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAssuranceMotoRoute = ServiceAssuranceMotoRouteImport.update({
  id: '/service/assurance-moto',
  path: '/service/assurance-moto',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAssuranceHabitationRoute =
  ServiceAssuranceHabitationRouteImport.update({
    id: '/service/assurance-habitation',
    path: '/service/assurance-habitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAssuranceDecennaleRoute =
  ServiceAssuranceDecennaleRouteImport.update({
    id: '/service/assurance-decennale',
    path: '/service/assurance-decennale',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAssuranceAutoRoute = ServiceAssuranceAutoRouteImport.update({
  id: '/service/assurance-auto',
  path: '/service/assurance-auto',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculateur-bonus-malus': typeof CalculateurBonusMalusRoute
  '/code-de-la-route': typeof CodeDeLaRouteRoute
  '/espace-client': typeof EspaceClientRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-cookies': typeof PolitiqueCookiesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/service/assurance-auto': typeof ServiceAssuranceAutoRoute
  '/service/assurance-decennale': typeof ServiceAssuranceDecennaleRoute
  '/service/assurance-habitation': typeof ServiceAssuranceHabitationRoute
  '/service/assurance-moto': typeof ServiceAssuranceMotoRoute
  '/service/assurance-prevoyance': typeof ServiceAssurancePrevoyanceRoute
  '/service/assurance-pro': typeof ServiceAssuranceProRoute
  '/service/assurance-sante': typeof ServiceAssuranceSanteRoute
  '/service/assurance-vtc': typeof ServiceAssuranceVtcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculateur-bonus-malus': typeof CalculateurBonusMalusRoute
  '/code-de-la-route': typeof CodeDeLaRouteRoute
  '/espace-client': typeof EspaceClientRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-cookies': typeof PolitiqueCookiesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/service/assurance-auto': typeof ServiceAssuranceAutoRoute
  '/service/assurance-decennale': typeof ServiceAssuranceDecennaleRoute
  '/service/assurance-habitation': typeof ServiceAssuranceHabitationRoute
  '/service/assurance-moto': typeof ServiceAssuranceMotoRoute
  '/service/assurance-prevoyance': typeof ServiceAssurancePrevoyanceRoute
  '/service/assurance-pro': typeof ServiceAssuranceProRoute
  '/service/assurance-sante': typeof ServiceAssuranceSanteRoute
  '/service/assurance-vtc': typeof ServiceAssuranceVtcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculateur-bonus-malus': typeof CalculateurBonusMalusRoute
  '/code-de-la-route': typeof CodeDeLaRouteRoute
  '/espace-client': typeof EspaceClientRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-cookies': typeof PolitiqueCookiesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/service/assurance-auto': typeof ServiceAssuranceAutoRoute
  '/service/assurance-decennale': typeof ServiceAssuranceDecennaleRoute
  '/service/assurance-habitation': typeof ServiceAssuranceHabitationRoute
  '/service/assurance-moto': typeof ServiceAssuranceMotoRoute
  '/service/assurance-prevoyance': typeof ServiceAssurancePrevoyanceRoute
  '/service/assurance-pro': typeof ServiceAssuranceProRoute
  '/service/assurance-sante': typeof ServiceAssuranceSanteRoute
  '/service/assurance-vtc': typeof ServiceAssuranceVtcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/blog'
    | '/calculateur-bonus-malus'
    | '/code-de-la-route'
    | '/espace-client'
    | '/mentions-legales'
    | '/politique-cookies'
    | '/politique-de-confidentialite'
    | '/blog/$slug'
    | '/service/assurance-auto'
    | '/service/assurance-decennale'
    | '/service/assurance-habitation'
    | '/service/assurance-moto'
    | '/service/assurance-prevoyance'
    | '/service/assurance-pro'
    | '/service/assurance-sante'
    | '/service/assurance-vtc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/blog'
    | '/calculateur-bonus-malus'
    | '/code-de-la-route'
    | '/espace-client'
    | '/mentions-legales'
    | '/politique-cookies'
    | '/politique-de-confidentialite'
    | '/blog/$slug'
    | '/service/assurance-auto'
    | '/service/assurance-decennale'
    | '/service/assurance-habitation'
    | '/service/assurance-moto'
    | '/service/assurance-prevoyance'
    | '/service/assurance-pro'
    | '/service/assurance-sante'
    | '/service/assurance-vtc'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/blog'
    | '/calculateur-bonus-malus'
    | '/code-de-la-route'
    | '/espace-client'
    | '/mentions-legales'
    | '/politique-cookies'
    | '/politique-de-confidentialite'
    | '/blog/$slug'
    | '/service/assurance-auto'
    | '/service/assurance-decennale'
    | '/service/assurance-habitation'
    | '/service/assurance-moto'
    | '/service/assurance-prevoyance'
    | '/service/assurance-pro'
    | '/service/assurance-sante'
    | '/service/assurance-vtc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalculateurBonusMalusRoute: typeof CalculateurBonusMalusRoute
  CodeDeLaRouteRoute: typeof CodeDeLaRouteRoute
  EspaceClientRoute: typeof EspaceClientRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueCookiesRoute: typeof PolitiqueCookiesRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  ServiceAssuranceAutoRoute: typeof ServiceAssuranceAutoRoute
  ServiceAssuranceDecennaleRoute: typeof ServiceAssuranceDecennaleRoute
  ServiceAssuranceHabitationRoute: typeof ServiceAssuranceHabitationRoute
  ServiceAssuranceMotoRoute: typeof ServiceAssuranceMotoRoute
  ServiceAssurancePrevoyanceRoute: typeof ServiceAssurancePrevoyanceRoute
  ServiceAssuranceProRoute: typeof ServiceAssuranceProRoute
  ServiceAssuranceSanteRoute: typeof ServiceAssuranceSanteRoute
  ServiceAssuranceVtcRoute: typeof ServiceAssuranceVtcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-cookies': {
      id: '/politique-cookies'
      path: '/politique-cookies'
      fullPath: '/politique-cookies'
      preLoaderRoute: typeof PolitiqueCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-client': {
      id: '/espace-client'
      path: '/espace-client'
      fullPath: '/espace-client'
      preLoaderRoute: typeof EspaceClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-de-la-route': {
      id: '/code-de-la-route'
      path: '/code-de-la-route'
      fullPath: '/code-de-la-route'
      preLoaderRoute: typeof CodeDeLaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculateur-bonus-malus': {
      id: '/calculateur-bonus-malus'
      path: '/calculateur-bonus-malus'
      fullPath: '/calculateur-bonus-malus'
      preLoaderRoute: typeof CalculateurBonusMalusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/assurance-vtc': {
      id: '/service/assurance-vtc'
      path: '/service/assurance-vtc'
      fullPath: '/service/assurance-vtc'
      preLoaderRoute: typeof ServiceAssuranceVtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/assurance-sante': {
      id: '/service/assurance-sante'
      path: '/service/assurance-sante'
      fullPath: '/service/assurance-sante'
      preLoaderRoute: typeof ServiceAssuranceSanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/assurance-pro': {
      id: '/service/assurance-pro'
      path: '/service/assurance-pro'
      fullPath: '/service/assurance-pro'
      preLoaderRoute: typeof ServiceAssuranceProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/assurance-prevoyance': {
      id: '/service/assurance-prevoyance'
      path: '/service/assurance-prevoyance'
      fullPath: '/service/assurance-prevoyance'
      preLoaderRoute: typeof ServiceAssurancePrevoyanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/assurance-moto': {
      id: '/service/assurance-moto'
      path: '/service/assurance-moto'
      fullPath: '/service/assurance-moto'
      preLoaderRoute: typeof ServiceAssuranceMotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/assurance-habitation': {
      id: '/service/assurance-habitation'
      path: '/service/assurance-habitation'
      fullPath: '/service/assurance-habitation'
      preLoaderRoute: typeof ServiceAssuranceHabitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/assurance-decennale': {
      id: '/service/assurance-decennale'
      path: '/service/assurance-decennale'
      fullPath: '/service/assurance-decennale'
      preLoaderRoute: typeof ServiceAssuranceDecennaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/assurance-auto': {
      id: '/service/assurance-auto'
      path: '/service/assurance-auto'
      fullPath: '/service/assurance-auto'
      preLoaderRoute: typeof ServiceAssuranceAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  CalculateurBonusMalusRoute: CalculateurBonusMalusRoute,
  CodeDeLaRouteRoute: CodeDeLaRouteRoute,
  EspaceClientRoute: EspaceClientRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueCookiesRoute: PolitiqueCookiesRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  ServiceAssuranceAutoRoute: ServiceAssuranceAutoRoute,
  ServiceAssuranceDecennaleRoute: ServiceAssuranceDecennaleRoute,
  ServiceAssuranceHabitationRoute: ServiceAssuranceHabitationRoute,
  ServiceAssuranceMotoRoute: ServiceAssuranceMotoRoute,
  ServiceAssurancePrevoyanceRoute: ServiceAssurancePrevoyanceRoute,
  ServiceAssuranceProRoute: ServiceAssuranceProRoute,
  ServiceAssuranceSanteRoute: ServiceAssuranceSanteRoute,
  ServiceAssuranceVtcRoute: ServiceAssuranceVtcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
